# Generated by Django 2.2.1 on 2019-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=160)),
                ('due_date', models.DateTimeField(verbose_name='date due')),
                ('percent_finished', models.CharField(max_length=5)),
            ],
        ),
    ]
